// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    /*
    tutorialSidebar: [
        {type: 'autogenerated', dirName: '.'}
    ],
  */
    // But you can create a sidebar manually

    tutorialSidebar: [
        // 1. Das Intro ganz oben (Dateiname: docs/intro.md)
        'intro',
        // 2. Kategorie für das "User-Manual"
        {
            type: 'category',
            label: 'Benutzerhandbuch',
            items: [
                'user-manual/installation',
                'user-manual/usermanual',
                'user-manual/dashboard',
                'user-manual/spieler-verwaltung',
                'user-manual/ticket-verwaltung',
                'user-manual/ziehungen',
            ],
        },
        // 3. Kategorie für den "code" Ordner
        {
            type: 'category',
            label: 'Programmierung & Code',
            items: [
                'code/code',
                'code/architektur',
                'code/models',
                'code/repositories',
                'code/services',
                'code/security-config',
                'code/view-controller',
                'code/kritische-konfigurationen',
            ],
        },
        'roadmap',
    ],

};

export default sidebars;
