services:
  backend:
    image: maven:3.9.0-eclipse-temurin-17
    working_dir: /app
    volumes:
      - .:/app
      - maven-repo:/root/.m2
      - h2-data:/data
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_SERVER_ADDRESS=0.0.0.0
    command: [ "./mvnw", "spring-boot:run" ]

  docusaurus:
    user: 1000:1001
    build:
      context: ./docusaurus
      dockerfile: Dockerfile
    ports:
      - "${DOCUSAURUS_PORT}:3000"
    volumes:
      - ./docusaurus:/app
      - "${DOCUSAURUS_VOLUME}:/app/node_modules"
    working_dir: /app
    command: [ "npm", "run", "start" ]

volumes:
  maven-repo:
  h2-data:
  docusaurus-data: