spring.application.name=lotto-springboot
server.port=8080
server.address=0.0.0.0
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
spring.datasource.url=jdbc:h2:file:./data/lotto;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=test
spring.datasource.password=test
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
# Zeigt jedes SQL-Statement in der Konsole
spring.jpa.show-sql=true
# Formatiert das SQL schön lesbar
spring.jpa.properties.hibernate.format_sql=true
# Zeigt die Werte der Parameter an (? -> echtes Datum/ID)
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
logging.level.org.springframework.security=DEBUG